#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

# Create folders
mkdir -p /tmp/bind/cache
chown -R 104 /tmp/bind/cache

# Mount USB Backup Drive
backupdest=/media/usb-backup
mkdir -p "$backupdest"
mount.exfat-fuse -o rw,uid=vyos,gid=vyattacfg /dev/disk/by-id/usb-Generic_Flash_Disk_D84B198C-0:0-part1 "$backupdest"
